### ISSUE TITLE
error messages - win 7 64, latest blender

### ISSUE THREAD

**Issue by blurymind** [Fweeb/blender_spritify#9]
I get this:
```
Traceback (most recent call last):
File "C:\Users\tod\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\spritify.py ", line 173, in execute
spritify(context.scene)
File "C:\Users\tod\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\spritify.py ", line 108, in spritify
os.remove(bpy.path.abspath(scene.spritesheet.filep ath))
PermissionError: [WinError 5] Access is denied: 'F:\\BACKUP\\WEB\\Dropbox\\BLENDS\\tilegen\\sheet\ \'


location: <unknown location>:-1
```
or this
```
Traceback (most recent call last):
File "C:\Users\tod\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\spritify.py ", line 173, in execute
spritify(context.scene)
File "C:\Users\tod\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\spritify.py ", line 108, in spritify
os.remove(bpy.path.abspath(scene.spritesheet.filep ath))
PermissionError: [WinError 5] Access is denied: 'F:\\BACKUP\\WEB\\Dropbox\\BLENDS\\tilegen\\sheet\ \'


location: <unknown location>:-1


Traceback (most recent call last):
File "C:\Users\tod\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\spritify.py ", line 173, in execute
spritify(context.scene)
File "C:\Users\tod\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\spritify.py ", line 127, in spritify
bpy.path.abspath(scene.spritesheet.filepath)])
File "C:\Program Files\Blender Foundation\Blender\2.77\python\lib\subprocess.py", line 560, in call
with Popen(*popenargs, **kwargs) as p:
File "C:\Program Files\Blender Foundation\Blender\2.77\python\lib\subprocess.py", line 950, in __init__
restore_signals, start_new_session)
File "C:\Program Files\Blender Foundation\Blender\2.77\python\lib\subprocess.py", line 1220, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified


location: <unknown location>:-1
```

**Comment by Fweeb** [comment]
Have you tried using this with a render path that isn't in a Dropbox folder? I'm suspecting that this might be a permissions problem on your machine and not a problem with Spritify.

**Comment by blurymind** [comment]
I have. Same error

**Comment by no-opponent** [comment]
Same issue. Win8.1 v2.77

**Comment by Fweeb** [comment]
Would it be possible for you (either of you) to supply a simple .blend file that I can use to reproduce this error? For instance, animate the default cube rotating 90 degrees in 10 frames.

**Comment by no-opponent** [comment]
Here; just created Suzanne, added some keyframes, a camera, rendered the animation and then tried to create the sprite sheet or gif
[untitled.zip](https://github.com/Fweeb/blender_spritify/files/296043/untitled.zip)

thanks for checking it out :)

**Comment by Dillybob92** [comment]
Easy fix boys, brand new to python (coming from nodejs background)

Replace line 127 with:

`bpy.path.abspath(scene.spritesheet.filepath)], shell = True)`

Make sure when you install ImageMagick you CHECK "Legacy" versions. Windows only obviously.

**Comment by khlorghaal** [comment]
I was getting the issue from ImageMagick not having the legacy options, spritify needs to mention that in its instructions
